<template>
    <section class="pt-[45px] pb-[80px]">
     <div class="first-container-var">
       <div class="row xl:px-0 px-3 main-terms-content-holder">
         <p class="sm:text-f-20 text-f-16 font-fw-400 sm:leading-[38px] leading-lh-28  text-sixth-color-var">Access to and use of this site (www.kerneltech.net) is provided by KernelTech. subject to the following terms:</p>
         <p class="sm:text-f-20 text-f-16 font-fw-400 sm:leading-[38px] leading-lh-28 mt-4  text-sixth-color-var ">By using this site you agree to be legally bound by these terms, which shall take effect immediately on your first use of the site. If you do not agree to be legally bound by all the following terms please do not access and/or use this site.</p>
         <p class="sm:text-f-20 text-f-16 font-fw-400 sm:leading-[38px] leading-lh-28 mt-4  text-sixth-color-var"> KernelTech may change these terms at any time by posting changes online. Please review these terms regularly to ensure you are aware of any changes made. Your continued use of this site after changes are posted means you agree to be legally bound by these terms as updated and/or amended.</p>
         <h4 class="md:text-f-25 sm:text-f-22 text-f-20 font-fw-700 sm:leading-lh-30 leading-lh-26 text-thirteenth-color-var md:mt-7 md:mb-[20px] sm:my-4 my-6 mt-8"> Use of www.KernelTech.net</h4>
         <p class="sm:text-f-20 text-f-16 font-fw-400 sm:leading-[38px] leading-lh-28 mt-4 text-sixth-color-var">You may not copy, reproduce, republish, download, post, broadcast, transmit, make available to the public, or otherwise use this site’s content in any way except for your own personal, non-commercial use. You also agree not to adapt, alter or create a derivative work from any content except for your own personal, non-commercial use. Any other use of this site’s content requires the prior written permission of KernelTech.</p>
         <p class="sm:text-f-20 text-f-16 font-fw-400 sm:leading-[38px] leading-lh-28 mt-4 text-sixth-color-var">You agree to use this site only for lawful purposes, and in a way that does not infringe the rights of, restrict or inhibit anyone else’s use and enjoyment of this site. Prohibited behavior includes harassing or causing distress or inconvenience to any person, transmitting obscene or offensive content or disrupting the normal flow of dialogue within this site.</p>
         <h4 class="md:text-f-25 sm:text-f-22 text-f-20 font-fw-700 sm:leading-lh-30  leading-lh-26 text-thirteenth-color-var md:mb-[20px] md:mt-7 sm:my-4 my-6 mt-8"> Disclaimers and limitation of liability</h4>
         <p class="sm:text-f-20 text-f-16 font-fw-400 sm:leading-[38px] leading-lh-28 mt-4 text-sixth-color-var">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
         <h4 class="md:text-f-25 sm:text-f-22 text-f-20 font-fw-700 sm:leading-lh-30  leading-lh-26 text-thirteenth-color-var  md:my-7 md:mb-[20px] sm:my-4 my-6 mt-8"> General</h4>
         <p class="sm:text-f-20 text-f-16 font-fw-400 sm:leading-[38px] leading-lh-28 mt-4 text-sixth-color-var">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. </p>
       </div>
     </div>
   </section>
</template>